-- MySQL Script generated by MySQL Workbench
-- Wed Jun 22 23:10:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projekt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projekt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projekt` DEFAULT CHARACTER SET utf8 ;
USE `projekt` ;

-- -----------------------------------------------------
-- Table `projekt`.`użytkownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`użytkownicy` (
  `id` VARCHAR(9) NOT NULL,
  `imię` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(45) NULL,
  `nr telefonu` INT NULL,
  `adres e-mail` VARCHAR(45) NULL,
  `opis` TEXT(255) NULL,
  `uprawnienia` INT NULL,
  `rola` INT NULL,
  `data_utworzenia` DATE NULL,
  `hasło` VARCHAR(45) NULL,
  `ilość_logowań` INT NULL,
  `ostatnia_zmiana_hasła` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`interpretacje_zjawisk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`interpretacje_zjawisk` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_obserwacji` INT NULL,
  `id_użytkownika` VARCHAR(8) NULL,
  `opis` TEXT(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`klasyfikacje_zjawisk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`klasyfikacje_zjawisk` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_zjawiska` INT NULL,
  `id_obserwacji` INT NULL,
  `id_użytkownika` VARCHAR(8) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`obserwacje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`obserwacje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_obserwatora` INT NULL,
  `id_użytkownika` VARCHAR(8) NULL,
  `uprawnienia` INT NULL,
  `data_czas` DATETIME NULL,
  `miejsce` VARCHAR(45) NULL,
  `opis` TEXT(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`obserwatorzy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`obserwatorzy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imię` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(45) NULL,
  `ulica` VARCHAR(45) NULL,
  `miasto` VARCHAR(45) NULL,
  `kod_pocztowy` VARCHAR(45) NULL,
  `nr_telefonu` INT NULL,
  `adres_email` VARCHAR(45) NULL,
  `nick` VARCHAR(45) NULL,
  `fotografia` TEXT(255) NULL,
  `opis` TEXT(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`załączniki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`załączniki` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` TEXT(255) NULL,
  `id_obserwacji` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`sms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`sms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_użytkownika` VARCHAR(8) NULL,
  `treść` VARCHAR(6) NULL,
  `czy_aktywny` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`wnioski_o_rejestrację`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`wnioski_o_rejestrację` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imię` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(45) NULL,
  `nr_telefonu` INT NULL,
  `adres_email` VARCHAR(45) NULL,
  `wiadomość` TEXT(255) NULL,
  `opis` TEXT(255) NULL,
  `rola` INT NULL,
  `uprawnienia` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`uprawnienia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`uprawnienia` (
  `id` INT NOT NULL,
  `opis` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`role` (
  `id` INT NOT NULL,
  `opis` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`logi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`logi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_użytkownika` VARCHAR(8) NULL,
  `data` DATETIME NULL,
  `aktywność` TEXT(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`zjawisko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`zjawisko` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `opis` TEXT(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `obserwatorzy` (`id`, `imię`, `nazwisko`, `ulica`, `miasto`, `kod_pocztowy`, `nr_telefonu`, `adres_email`, `nick`, `fotografia`, `opis`) VALUES (NULL, 'Marta', 'Pyssa', 'Kwiatowa 14', 'Poznań', '40-500', '809768876', 'm.pyssa@poczta.com', 'mpyssa', 'image/mpyssa.png', NULL), (NULL, 'Aleksander', 'Kaczor', 'Pomarańczowa 12', 'Płock', '11-002', '777123123', 'akaczor@poczta.org', 'akaczor', 'image/akaczor.png', NULL)
INSERT INTO `obserwacje` (`id`, `id_obserwatora`, `id_użytkownika`, `uprawnienia`, `data_czas`, `miejsce`, `opis`) VALUES (NULL, '1', 'kaan54321', '3', '2022-05-17 23:20:41', 'Góry Sowie', 'Na niebie systematycznie rozbłyskiwało coś podobnego do gwiazd. Światło było cyklicznie raz bardziej intensywne, raz mniej. Obiekty nie przemieszały się. '), (NULL, '2', 'kaan54321', '2', '2022-06-07 11:20:41', 'Kołobrzeg', 'Podczas sztormu niebo zrobiło się czerwone i w oddali było słychać dziwne dźwięki, jakby latającego talerza. To był falujący dźwięk. ')
INSERT INTO `użytkownicy` (`id`, `imię`, `nazwisko`, `nr telefonu`, `adres e-mail`, `opis`, `uprawnienia`, `rola`, `data_utworzenia`, `hasło`, `ilość_logowań`, `ostatnia_zmiana_hasła`) VALUES ('kaan54321', 'Karol', 'Andrzejak', '556112334', 'k.andrzejak@projekt.pl', 'Profesor', '2', '3', '2022-06-22', 'kaan123', NULL, NULL)
INSERT INTO `role` (`id`, `opis`) VALUES ('3', 'Administrator Systemu'), ('2', 'Administrator Danych'), ('1', 'Analityk'), ('0', 'Czytelnik')
INSERT INTO `uprawnienia` (`id`, `opis`) VALUES ('0', 'dane jawne'), ('1', 'dane poufne'), ('2', 'dane tajne'), ('3', 'dane ściśle tajne')